Add Deno guide
excaliburjs/excaliburjs.github.io pull request #113
Opened 2021-10-29 14:51 UTC by Return180bpm

Added a guide for setting up excalibur in a Deno environment, as dicussed in [#2062](https://github.com/excaliburjs/Excalibur/issues/2062).

2021-10-29 21:20 UTC, eonarheim requested changes
@Return180bpm Thank you so much for this Deno addition!

* Couple small text tweaks suggested
* Remove the `package-lock.json` changes there aren't any `package.json` updates

2021-10-29 21:20 UTC, eonarheim commented on docs/02.1-bundlers.mdx
> +For Excalibur to work in a Deno envirionment, use a Content Delivery Network for making Node.js packages compatible with Deno: two popular ones are [esm.sh](https://esm.sh/) and [skypack.dev](https:/
```suggestion
For Excalibur to work in a Deno environment, use a Content Delivery Network for making Node.js packages compatible with Deno: two popular ones are [esm.sh](https://esm.sh/) and [skypack.dev](https://www.skypack.dev/).
```

2021-10-29 21:20 UTC, eonarheim commented on docs/02.1-bundlers.mdx
> +To keep it simple, we use esm.sh in the following examples, but feel free to make your own choice - at the time of writing the procedure for esm.sh and skypack.dev is nearly identical (for a differen
```suggestion
To keep it simple, we use `esm.sh` in the following examples, but feel free to make your own choice - at the time of writing the procedure for `esm.sh` and `skypack.dev` is nearly identical (for a difference, see the section [Types and IntelliSense](#types-and-intellisense)).
```

2021-10-29 21:20 UTC, eonarheim commented on docs/02.1-bundlers.mdx
> +We have tested the following examples with version 0.26.0-alpha.264 of the excalibur package. We recommend you run at least that version for this to work. You can get [the latest excalibur version on
We'll cut a point release soon, I'll make a note so I don't forget to update this :+1:

2021-10-29 21:20 UTC, eonarheim commented on docs/02.1-bundlers.mdx
> +**If you're using skypack.dev**, you might also need to add the `?dts` query parameter to the package name. your import should read something like this:
👍

2021-10-30 10:47 UTC, Return180bpm commented
Hey @eonarheim, thank You for the speedy review and your corrections! They've been applied.

I also added a pretty big commit with changes to /docs/installation. I should have put this in here to begin with, but I forgot. It basically adds a section about CDNs and links to the newly written guide. (I also reformatted the intro to make it more readable.)

2021-10-30 14:01 UTC, eonarheim commented on docs/01-installation.mdx
> +There are several ways you can get Excalibur:
👍

2021-10-30 14:03 UTC, eonarheim approved these changes
@Return180bpm Thanks! This is great!

2021-10-30 14:04 UTC, merged